[package]
name = "mingo"
version = "1.0.0"
description = "Runtime Initialization — Chapter 02"
keywords = ["runtime-init"]
authors = ["Andre Richter <andre.o.richter@gmail.com>"]
edition = "2024"

[profile.release]
lto = true

[features]
default = []
bsp_rpi3 = []
bsp_rpi4 = []
boot_trace = []

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false

##--------------------------------------------------------------------------------------------------
## Dependencies
##--------------------------------------------------------------------------------------------------

[dependencies]

# Platform specific dependencies
[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0.0"
