name: BSP-RPi3

on:
    push:
    pull_request:
    schedule:
        - cron: "0 5 * * *"

jobs:
    build:
        name: Build kernels
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3
            - name: Set up Rust tools
              run: |
                  cargo install cargo-binutils rustfilt
            - name: Run
              run: BSP=rpi3 make
